<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ui" nsURI="http://www.saiman.co.uk/eclipse/2018/UISaiman/ui"
    nsPrefix="saiman.ui">
  <eClassifiers xsi:type="ecore:EDataType" name="MediaType" instanceClassName="uk.co.saiman.data.format.MediaType"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TransferFormat" instanceClassName="uk.co.saiman.eclipse.ui.TransferFormat"
      serializable="false">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cell">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediaTypes" upperBound="-1"
        eType="#//MediaType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributions" upperBound="-1"
        eType="#//CellContribution" containment="true" eOpposite="#//CellContribution/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="popupMenu" eType="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/menu/PopupMenu"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transferFormats" upperBound="-1"
        transient="true" derived="true">
      <eGenericType eClassifier="#//TransferFormat">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/UILabel"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/Context"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//Contribution"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/ElementContainer">
      <eTypeArguments eClassifier="#//Cell"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//commands/HandlerContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tree">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/Context"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//Contribution"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/ElementContainer">
      <eTypeArguments eClassifier="#//Cell"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//commands/HandlerContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellContribution" eSuperTypes="../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/Context ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//Contribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Cell"
        eOpposite="#//Cell/contributions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HandledCell" eSuperTypes="#//Cell ../../org.eclipse.e4.ui.model.workbench/model/UIElements.ecore#//ui/menu/HandledItem"/>
</ecore:EPackage>
